
CREATE DATABASE IF NOT EXISTS crawler;
USE DATABASE crawler;

CREATE TABLE IF NOT EXISTS links
(
	linkID INT NOT NULL AUTO INCREMENT, 
	url TEXT NOT NULL, 
	PRIMARY KEY(linkID)
) DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;